const menu = {
    list() {
        return [
    {
        "backMenu":[
        ],
        "frontMenu":[
        ],
        "hasBackLogin":"是",
        "hasBackRegister":"否",
        "hasFrontLogin":"否",
        "hasFrontRegister":"否",
        "roleName":"管理员",
        "tableName":"users"
    },
    {
        "backMenu":[
            {
                "child":[
                    {
						"appFrontIcon":"cuIcon-message",
                        "buttons":[
                            "查看"
                        ],
                        "menu":"客服聊天",
                        "menuJump":"列表",
                        "tableName":"chat"
                    }
                ],
                "menu":"客服聊天"
            }
			,
			{
                "child":[
                    {
						"appFrontIcon":"cuIcon-form",
                        "buttons":[
                            "查看"
                        ],
                        "menu":"电影信息",
                        "menuJump":"列表",
                        "tableName":"dianying"
                    }
                ],
                "menu":"电影信息"
            }
            ,
            {
                "child":[
                    {
						"appFrontIcon":"cuIcon-favor",
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"电影收藏",
                        "menuJump":"列表",
                        "tableName":"dianyingCollection"
                    }
                ],
                "menu":"电影收藏"
            }
            ,
            {
                "child":[
                    {
						"appFrontIcon":"cuIcon-evaluate",
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"电影评价",
                        "menuJump":"列表",
                        "tableName":"dianyingLiuyan"
                    }
                ],
                "menu":"电影评价"
            }
            ,
            {
                "child":[
                    {
						"appFrontIcon":"cuIcon-activity",
                        "buttons":[
                            "查看"
                        ],
                        "menu":"通知公告",
                        "menuJump":"列表",
                        "tableName":"news"
                    }
                ],
                "menu":"通知公告"
            }
        ],
        "frontMenu":[
        ],
        "hasBackLogin":"是",
        "hasBackRegister":"否",
        "hasFrontLogin":"是",
        "hasFrontRegister":"是",
        "roleName":"用户",
        "tableName":"yonghu"
    }
]

	}
}
export default menu;
